on:
  push:
    branches:
      - main
name: Deploy to Github Pages
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build
        run: |
          npm run build
          touch dist/.nojekyll
          echo "endless.slashdev.space" > CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist